typography_spectrum: 0.7965807295404375
color:
  brandStrength: 0.2557767634280026
  lightness: 0.7129830138292164
  saturation: 0.13902315450832248
  rhythmicContrast: 0.7777276393026114
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
layout_spectrum: 0.8361393525265157
author:
  name: Santiago
  email: pastiche@gns.net
logo: null
name: 'Letras, Música y Cine'
navigation:
  - id: 3d4dd780-b730-4d0d-8b58-b2b95f139541
    name: David Gilmour - Today (Official Music Video)
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bb59617-6cbd-4155-a1fa-f5e6e3251458.jpg
title: Un pastiche
