typography_spectrum: 0.6579860288184136
color:
  brandStrength: 0.3106922919396311
  lightness: 0.8172249279450625
  saturation: 0.47130643716081977
  rhythmicContrast: 0.7316940794698894
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.8361393525265157
author:
  name: Santiago
  email: pastiche@gns.net
logo: null
name: 'Letras, Música y Cine'
navigation:
  - id: 3d4dd780-b730-4d0d-8b58-b2b95f139541
    name: David Gilmour - Today (Official Music Video)
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bb59617-6cbd-4155-a1fa-f5e6e3251458.jpg
title: Un pastiche
