typography_spectrum: 0.9699957077391446
color:
  brandStrength: 0.870677886530757
  lightness: 0.3839139910414815
  saturation: 0.15726225404068828
  rhythmicContrast: 0.450784059939906
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.11672944412566721
author:
  name: Santiago
  email: pastiche@gns.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/92d08570-0e47-495b-88e0-92822133b481.jpg
name: 'Letras, Música y Cine'
navigation:
  - id: 3d4dd780-b730-4d0d-8b58-b2b95f139541
    name: David Gilmour - Today (Official Music Video)
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bb59617-6cbd-4155-a1fa-f5e6e3251458.jpg
title: PASTICHE
description: 'Letras, Música y Cine'
